[package]
name = "evm-dev-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
hex = "0.4.3"
primitive-types = "0.13.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
